name: Python application

on:
  
  schedule:
    - cron: '01 22 * * *'
  watch:
    types: [started]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'   
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: apt-get
      run: |
        python -m pip install --upgrade pip
        sudo apt-get -y install wget net-tools
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Test with pytest
      run: |
        python3 searchmap.py -u  116.204.168.140 -p

